# **Notebook 3 - Basket Analysis**

Afonso Fernandes 20241710, Lourenço Lima 20241711, Lucas Casimiro 20241796

## Imports

In [10]:
import os
import sys
import warnings
from pathlib import Path

def _find_project_root(start, marker="requirements.txt"):
    path = Path(start).resolve()
    for candidate in [path] + list(path.parents):
        if (candidate / marker).exists():
            return str(candidate)
    raise RuntimeError(f"Could not find project root (marker={marker!r}, searched from {start})")

PROJECT_ROOT = _find_project_root(os.path.abspath("."))
os.chdir(PROJECT_ROOT)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

warnings.filterwarnings("ignore")

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import importlib
from functions.basket import *

from functions.preprocessing import FEATURE_COLS
from functions.basket import *
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# **1. Merging data**

In [50]:
customer_basket = pd.read_csv('data/customer_basket.csv')
customer = pd.read_csv('data/ci_clustered.csv')

In [51]:
merged_data = pd.merge(customer_basket, customer, on="customer_id", how="inner")
merged_data

,invoice_id,list_of_goods,customer_id,customer_name,customer_gender,kids_home,teens_home,number_complaints,distinct_stores_visited,lifetime_spend_groceries,...,share_nonalcohol_drinks,share_alcohol_drinks,share_meat,share_fish,share_hygiene,share_videogames,share_petfood,dietary_preference,final_cluster_nr,final_cluster_label
0,3700630,"['chicken', 'rice', 'pepper', 'whole wheat ric...",12912,Msc. George Davis,male,1.0,0.0,2.0,3.0,13092.0,...,0.020800,0.020462,0.052198,0.032525,0.036359,0.009977,0.028129,omnivore,4,Gamers
1,10242376,"['low fat yogurt', 'tomatoes', 'pepper', 'aspa...",22853,Patricia Silva,female,1.0,1.0,1.0,6.0,15518.0,...,0.007247,0.004986,0.074887,0.014905,0.019531,0.001902,0.019377,omnivore,4,Gamers
2,91550,"['cake', 'tomatoes', 'pancakes', 'iPad', 'fina...",19,Phd. Evelyn Quinn,female,1.0,2.0,3.0,3.0,8264.0,...,0.026508,0.034148,0.068031,0.093343,0.054411,0.011161,0.035411,omnivore,0,Tech enthusiasts
3,3137503,"['cereals', 'megaman zero', 'final fantasy XIX...",10995,Msc. David Stupar,male,3.0,4.0,0.0,2.0,24573.0,...,0.028657,0.061240,0.049489,0.041370,0.028016,0.010897,0.001415,omnivore,2,Average customer
4,7165061,"['rice', 'frozen smoothie', 'black tea', 'tea'...",27807,Noel Froelich,female,6.0,1.0,1.0,2.0,26093.0,...,0.025166,0.036475,0.042300,0.032471,0.052298,0.006285,0.011989,omnivore,2,Average customer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98699,7685930,"['yams', 'airpods', 'shrimp']",21357,Frank Erdmann,male,1.0,0.0,0.0,8.0,15106.0,...,0.013355,0.038252,0.032097,0.023358,0.032536,0.000824,0.012916,omnivore,4,Gamers
98700,2998960,"['cake', 'chocolate bread', 'cologne', 'beer',...",7817,Marian Mitchell,female,0.0,0.0,1.0,2.0,13164.0,...,0.014037,0.027575,0.021447,0.033921,0.008504,0.061652,0.007409,omnivore,1,Clean and healthy
98701,4409376,"['chicken', 'frozen smoothie', 'milk', 'body s...",35497,Judith Roane,female,0.0,1.0,0.0,2.0,6439.0,...,0.050386,0.012645,0.098263,0.035811,0.044015,0.004633,0.040927,omnivore,0,Tech enthusiasts
98702,3650163,"['metroid fusion', 'cat food', 'melons', 'ring...",13412,Phd. Mark Lunde,male,1.0,1.0,0.0,2.0,17407.0,...,0.021467,0.020131,0.005159,0.000967,0.015110,0.000000,0.010135,omnivore,4,Gamers
98703,12236507,"['cake', 'strong cheese', 'meatballs', 'tomato...",23325,Betty Pritchard,female,0.0,1.0,0.0,5.0,9242.0,...,0.061595,0.017188,0.036431,0.001809,0.000000,0.010362,0.025987,omnivore,4,Gamers

# **2. Dataframe by cluster**

In [52]:
cluster_dataframes = {
    cluster: group
    for cluster, group in merged_data.groupby("final_cluster_label", sort=False)}

**NOTE**: Here is the code where we ran after running the association rules the first time and seeing unrelated results to the vegan cluster. We copied the output to show why we needed to separate the cluster and redo the clustering process. The output was originated from checking the `dietary_preference` column distribution in the vegan cluster.

--- Vegans ---

dietary_preference

omnivore       3615

vegetarian     3019

carnivore         1

pescatarian       1

Name: count, dtype: int64

## Parameter by cluster

In [60]:
params_by_cluster = {
        "Bargain hunters": {"min_support": 0.01, "min_threshold": 1, "min_confidence": 0.10},

        "Tech enthusiasts": {"min_support": 0.02, "min_threshold": 1.5, "min_confidence": 0.1},

        "Big families (big spenders)": {"min_support": 0.01, "min_threshold": 1.5, "min_confidence": 0.1},

        "Clean and healthy": {"min_support": 0.01, "min_threshold": 1, "min_confidence": 0.10},
        
        "Average customer": {"min_support": 0.03, "min_threshold": 1, "min_confidence": 0.10},

        "Gamers": {"min_support": 0.03, "min_threshold": 1.5, "min_confidence": 0.1},
        
        "Loyal big spenders": {"min_support": 0.02, "min_threshold": 1, "min_confidence": 0.10},

        "Karens": {"min_support": 0.08, "min_threshold": 1.5, "min_confidence": 0.1},

        "Vegans": {"min_support": 0.05, "min_threshold": 1, "min_confidence": 0.1}}

# **3. Association rules**

Note: some baskets were lost due to outlier removal, we decided to keep it with less baskets to guarantee previous clean results.

In [61]:
generate_rules_for_all_clusters = generate_rules_for_all_clusters
generate_association_rules = generate_association_rules

In [62]:
all_cluster_rules = generate_rules_for_all_clusters(
    cluster_dataframes=cluster_dataframes,
    params_by_cluster=params_by_cluster
)

for cluster_name, rules in all_cluster_rules.items():
    print(f"CLUSTER: {cluster_name}")

    if rules.empty:
        print("No rules found.")
    else:
        display(rules.head(30))

CLUSTER: Gamers

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({bluetooth headphones}),frozenset({energy drink}),0.126229,0.124297,0.038199,0.302618,2.434634,1.0,0.022509,1.255701,0.674388,0.179907,0.203632,0.304969
1,frozenset({energy drink}),frozenset({bluetooth headphones}),0.124297,0.126229,0.038199,0.307320,2.434634,1.0,0.022509,1.261437,0.672900,0.179907,0.207253,0.304969
2,frozenset({airpods}),frozenset({bluetooth headphones}),0.210824,0.126229,0.059316,0.281352,2.228907,1.0,0.032704,1.215854,0.698640,0.213568,0.177533,0.375630
3,frozenset({bluetooth headphones}),frozenset({airpods}),0.126229,0.210824,0.059316,0.469908,2.228907,1.0,0.032704,1.488753,0.631000,0.213568,0.328297,0.375630
4,frozenset({energy drink}),frozenset({airpods}),0.124297,0.210824,0.058028,0.466851,2.214405,1.0,0.031823,1.480215,0.626253,0.209418,0.324423,0.371048
5,frozenset({airpods}),frozenset({energy drink}),0.210824,0.124297,0.058028,0.275244,2.214405,1.0,0.031823,1.208273,0.694917,0.209418,0.172373,0.371048
6,frozenset({pancakes}),frozenset({airpods}),0.079660,0.210824,0.031589,0.396552,1.880957,1.0,0.014795,1.307777,0.508894,0.122016,0.235343,0.273194
7,frozenset({airpods}),frozenset({pancakes}),0.210824,0.079660,0.031589,0.149837,1.880957,1.0,0.014795,1.082545,0.593475,0.122016,0.076251,0.273194
8,frozenset({energy bar}),frozenset({airpods}),0.090261,0.210824,0.035753,0.396101,1.878818,1.0,0.016723,1.306800,0.514159,0.134746,0.234772,0.282843
9,frozenset({airpods}),frozenset({energy bar}),0.210824,0.090261,0.035753,0.169585,1.878818,1.0,0.016723,1.095522,0.592708,0.134746,0.087194,0.282843
10,frozenset({protein bar}),frozenset({airpods}),0.092407,0.210824,0.036225,0.392011,1.859419,1.0,0.016743,1.298010,0.509257,0.135670,0.229590,0.281918
11,frozenset({airpods}),frozenset({protein bar}),0.210824,0.092407,0.036225,0.171824,1.859419,1.0,0.016743,1.095894,0.585672,0.135670,0.087503,0.281918
12,frozenset({iphone 10}),frozenset({airpods}),0.092279,0.210824,0.034422,0.373023,1.769354,1.0,0.014967,1.258700,0.479026,0.128115,0.205529,0.268148
13,frozenset({airpods}),frozenset({iphone 10}),0.210824,0.092279,0.034422,0.163274,1.769354,1.0,0.014967,1.084848,0.550983,0.128115,0.078212,0.268148
14,frozenset({laptop}),frozenset({airpods}),0.094553,0.210824,0.034980,0.369950,1.754777,1.0,0.015046,1.252560,0.475044,0.129365,0.201635,0.267935
15,frozenset({airpods}),frozenset({laptop}),0.210824,0.094553,0.034980,0.165920,1.754777,1.0,0.015046,1.085563,0.545034,0.129365,0.078819,0.267935

CLUSTER: Tech enthusiasts

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({energy drink}),frozenset({airpods}),0.081975,0.158616,0.030474,0.371747,2.343686,1.0,0.017471,1.339244,0.624516,0.145033,0.253310,0.281935
1,frozenset({airpods}),frozenset({energy drink}),0.158616,0.081975,0.030474,0.192123,2.343686,1.0,0.017471,1.136343,0.681403,0.145033,0.119984,0.281935
2,frozenset({bluetooth headphones}),frozenset({airpods}),0.087003,0.158616,0.031388,0.360771,2.274483,1.0,0.017588,1.316247,0.613737,0.146515,0.240264,0.279329
3,frozenset({airpods}),frozenset({bluetooth headphones}),0.158616,0.087003,0.031388,0.197887,2.274483,1.0,0.017588,1.138240,0.665974,0.146515,0.121450,0.279329
4,frozenset({pancakes}),frozenset({airpods}),0.068719,0.158616,0.020722,0.301552,1.901140,1.0,0.009822,1.204648,0.508976,0.100295,0.169882,0.216098
5,frozenset({airpods}),frozenset({pancakes}),0.158616,0.068719,0.020722,0.130644,1.901140,1.0,0.009822,1.071231,0.563358,0.100295,0.066494,0.216098
6,frozenset({iphone 10}),frozenset({airpods}),0.071918,0.158616,0.021484,0.298729,1.883340,1.0,0.010077,1.199798,0.505374,0.102770,0.166526,0.217088
7,frozenset({airpods}),frozenset({iphone 10}),0.158616,0.071918,0.021484,0.135447,1.883340,1.0,0.010077,1.073481,0.557449,0.102770,0.068451,0.217088
8,frozenset({airpods}),frozenset({laptop}),0.158616,0.090507,0.023465,0.147935,1.634504,1.0,0.009109,1.067398,0.461375,0.103984,0.063142,0.203597
9,frozenset({laptop}),frozenset({airpods}),0.090507,0.158616,0.023465,0.259259,1.634504,1.0,0.009109,1.135868,0.426824,0.103984,0.119616,0.203597
10,frozenset({airpods}),frozenset({energy bar}),0.158616,0.081822,0.020722,0.130644,1.596674,1.0,0.007744,1.056158,0.444147,0.094313,0.053172,0.191951
11,frozenset({energy bar}),frozenset({airpods}),0.081822,0.158616,0.020722,0.253259,1.596674,1.0,0.007744,1.126741,0.407000,0.094313,0.112484,0.191951

CLUSTER: Average customer

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"frozenset({eggs, butter})",frozenset({honey}),0.144106,0.213762,0.039763,0.275930,1.290826,1.0,0.008959,1.085858,0.263236,0.125000,0.079070,0.230973
1,frozenset({honey}),"frozenset({eggs, butter})",0.213762,0.144106,0.039763,0.186016,1.290826,1.0,0.008959,1.051487,0.286557,0.125000,0.048966,0.230973
2,"frozenset({honey, butter})",frozenset({eggs}),0.087845,0.358291,0.039763,0.452648,1.263354,1.0,0.008289,1.172389,0.228532,0.097849,0.147041,0.281814
3,frozenset({eggs}),"frozenset({honey, butter})",0.358291,0.087845,0.039763,0.110980,1.263354,1.0,0.008289,1.026022,0.324846,0.097849,0.025362,0.281814
4,"frozenset({tea, cereals})",frozenset({fresh bread}),0.087140,0.371968,0.040891,0.469256,1.261547,1.0,0.008478,1.183303,0.227113,0.097775,0.154908,0.289594
5,frozenset({fresh bread}),"frozenset({tea, cereals})",0.371968,0.087140,0.040891,0.109932,1.261547,1.0,0.008478,1.025606,0.330115,0.097775,0.024967,0.289594
6,"frozenset({fresh bread, cereals})",frozenset({tea}),0.153976,0.211083,0.040891,0.265568,1.258121,1.0,0.008389,1.074186,0.242503,0.126142,0.069063,0.229644
7,frozenset({tea}),"frozenset({fresh bread, cereals})",0.211083,0.153976,0.040891,0.193721,1.258121,1.0,0.008389,1.049294,0.260057,0.126142,0.046978,0.229644
8,"frozenset({eggs, oatmeal})",frozenset({cereals}),0.084179,0.377045,0.039481,0.469012,1.243916,1.0,0.007742,1.173200,0.214111,0.093614,0.147630,0.286862
9,frozenset({cereals}),"frozenset({eggs, oatmeal})",0.377045,0.084179,0.039481,0.104712,1.243916,1.0,0.007742,1.022934,0.314769,0.093614,0.022420,0.286862
10,"frozenset({eggs, honey})",frozenset({butter}),0.087704,0.364636,0.039763,0.453376,1.243366,1.0,0.007783,1.162342,0.214548,0.096377,0.139668,0.281212
11,frozenset({butter}),"frozenset({eggs, honey})",0.364636,0.087704,0.039763,0.109049,1.243366,1.0,0.007783,1.023957,0.308062,0.096377,0.023396,0.281212
12,"frozenset({oatmeal, cereals})",frozenset({eggs}),0.089538,0.358291,0.039481,0.440945,1.230689,1.0,0.007401,1.147846,0.205881,0.096685,0.128803,0.275569
13,frozenset({eggs}),"frozenset({oatmeal, cereals})",0.358291,0.089538,0.039481,0.110193,1.230689,1.0,0.007401,1.023213,0.292106,0.096685,0.022687,0.275569
14,frozenset({cereals}),"frozenset({eggs, tea})",0.377045,0.082205,0.037930,0.100598,1.223745,1.0,0.006935,1.020450,0.293499,0.090027,0.020040,0.281002
15,"frozenset({eggs, tea})",frozenset({cereals}),0.082205,0.377045,0.037930,0.461407,1.223745,1.0,0.006935,1.156634,0.199213,0.090027,0.135422,0.281002
16,frozenset({cereals}),"frozenset({oatmeal, butter})",0.377045,0.081077,0.037366,0.099102,1.222321,1.0,0.006796,1.020008,0.291970,0.088807,0.019616,0.279986
17,"frozenset({oatmeal, butter})",frozenset({cereals}),0.081077,0.377045,0.037366,0.460870,1.222321,1.0,0.006796,1.155482,0.197932,0.088807,0.134560,0.279986
18,"frozenset({butter, cereals})",frozenset({eggs}),0.151438,0.358291,0.066131,0.436685,1.218800,1.0,0.011872,1.139166,0.211559,0.149078,0.122165,0.310629
19,frozenset({eggs}),"frozenset({butter, cereals})",0.358291,0.151438,0.066131,0.184573,1.218800,1.0,0.011872,1.040635,0.279755,0.149078,0.039048,0.310629
20,"frozenset({fresh bread, eggs})",frozenset({cereals}),0.141850,0.377045,0.065144,0.459245,1.218011,1.0,0.011660,1.152010,0.208576,0.143567,0.131952,0.316010
21,frozenset({cereals}),"frozenset({fresh bread, eggs})",0.377045,0.141850,0.065144,0.172775,1.218011,1.0,0.011660,1.037384,0.287323,0.143567,0.036037,0.316010
22,frozenset({cereals}),"frozenset({eggs, butter})",0.377045,0.144106,0.066131,0.175393,1.217108,1.0,0.011796,1.037941,0.286346,0.145336,0.036554,0.317148
23,"frozenset({eggs, butter})",frozenset({cereals}),0.144106,0.377045,0.066131,0.458904,1.217108,1.0,0.011796,1.151285,0.208414,0.145336,0.131405,0.317148
24,frozenset({eggs}),"frozenset({tea, cereals})",0.358291,0.087140,0.037930,0.105864,1.214865,1.0,0.006708,1.020940,0.275612,0.093080,0.020511,0.270569
25,"frozenset({tea, cereals})",frozenset({eggs}),0.087140,0.358291,0.037930,0.435275,1.214865,1.0,0.006708,1.136321,0.193746,0.093080,0.119967,0.270569
26,"frozenset({honey, cereals})",frozenset({eggs}),0.088832,0.358291,0.038635,0.434921,1.213875,1.0,0.006807,1.135609,0.193370,0.094581,0.119415,0.271376
27,frozenset({eggs}),"frozenset({honey, cereals})",0.358291,0.088832,0.038635,0.107832,1.213875,1.0,0.006807,1.021295,0.274567,0.094581,0.020851,0.271376
28,frozenset({butter}),"frozenset({bacon, cereals})",0.364636,0.090525,0.039904,0.109435,1.208903,1.0,0.006896,1.021235,0.271977,0.096095,0.020793,0.275123
29,"frozenset({bacon, cereals})",frozenset({butter}),0.090525,0.364636,0.039904,0.440810,1.208903,1.0,0.006896,1.136222,0.190004,0.096095,0.119890,0.275123

CLUSTER: Bargain hunters

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({energy drink}),frozenset({airpods}),0.070101,0.101257,0.017032,0.242963,2.399477,1.0,0.009934,1.187185,0.627210,0.110363,0.157672,0.205584
1,frozenset({airpods}),frozenset({energy drink}),0.101257,0.070101,0.017032,0.168205,2.399477,1.0,0.009934,1.117943,0.648953,0.110363,0.105500,0.205584
2,frozenset({bluetooth headphones}),frozenset({energy drink}),0.070828,0.070101,0.011839,0.167155,2.384503,1.0,0.006874,1.116534,0.624885,0.091714,0.104371,0.168022
3,frozenset({energy drink}),frozenset({bluetooth headphones}),0.070101,0.070828,0.011839,0.168889,2.384503,1.0,0.006874,1.117988,0.624396,0.091714,0.105536,0.168022
4,frozenset({airpods}),frozenset({bluetooth headphones}),0.101257,0.070828,0.014436,0.142564,2.012830,1.0,0.007264,1.083664,0.559878,0.091568,0.077205,0.173188
5,frozenset({bluetooth headphones}),frozenset({airpods}),0.070828,0.101257,0.014436,0.203812,2.012830,1.0,0.007264,1.128808,0.541543,0.091568,0.114110,0.173188
6,frozenset({pancakes}),frozenset({airpods}),0.052238,0.101257,0.010178,0.194831,1.924131,1.0,0.004888,1.116217,0.506757,0.071014,0.104117,0.147672
7,frozenset({airpods}),frozenset({pancakes}),0.101257,0.052238,0.010178,0.100513,1.924131,1.0,0.004888,1.053669,0.534396,0.071014,0.050936,0.147672
8,frozenset({airpods}),frozenset({laptop}),0.101257,0.078409,0.013605,0.134359,1.713566,1.0,0.005665,1.064634,0.463338,0.081926,0.060710,0.153934
9,frozenset({laptop}),frozenset({airpods}),0.078409,0.101257,0.013605,0.173510,1.713566,1.0,0.005665,1.087422,0.451851,0.081926,0.080394,0.153934
10,frozenset({extra dark chocolate}),frozenset({airpods}),0.070932,0.101257,0.012255,0.172767,1.706231,1.0,0.005072,1.086446,0.445514,0.076623,0.079567,0.146896
11,frozenset({airpods}),frozenset({extra dark chocolate}),0.101257,0.070932,0.012255,0.121026,1.706231,1.0,0.005072,1.056992,0.460546,0.076623,0.053919,0.146896
12,frozenset({protein bar}),frozenset({airpods}),0.095233,0.101257,0.015370,0.161396,1.593929,1.0,0.005727,1.071713,0.411840,0.084862,0.066915,0.156595
13,frozenset({airpods}),frozenset({protein bar}),0.101257,0.095233,0.015370,0.151795,1.593929,1.0,0.005727,1.066684,0.414600,0.084862,0.062515,0.156595
14,frozenset({protein bar}),frozenset({bluetooth headphones}),0.095233,0.070828,0.010593,0.111232,1.570463,1.0,0.003848,1.045461,0.401479,0.068136,0.043484,0.130396
15,frozenset({bluetooth headphones}),frozenset({protein bar}),0.070828,0.095233,0.010593,0.149560,1.570463,1.0,0.003848,1.063881,0.390934,0.068136,0.060045,0.130396
16,frozenset({ring light}),frozenset({airpods}),0.071451,0.101257,0.011320,0.158430,1.564641,1.0,0.004085,1.067937,0.388645,0.070142,0.063615,0.135113
17,frozenset({airpods}),frozenset({ring light}),0.101257,0.071451,0.011320,0.111795,1.564641,1.0,0.004085,1.045422,0.401534,0.070142,0.043448,0.135113
18,frozenset({airpods}),frozenset({samsung galaxy 10}),0.101257,0.078721,0.012255,0.121026,1.537409,1.0,0.004284,1.048130,0.388937,0.073065,0.045920,0.138349
19,frozenset({samsung galaxy 10}),frozenset({airpods}),0.078721,0.101257,0.012255,0.155673,1.537409,1.0,0.004284,1.064449,0.379423,0.073065,0.060547,0.138349

CLUSTER: Clean and healthy

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({bluetooth headphones}),"frozenset({airpods, energy drink})",0.068334,0.034755,0.011921,0.174447,5.019359,1.0,0.009546,1.169211,0.859505,0.130755,0.144722,0.258721
1,"frozenset({airpods, energy drink})",frozenset({bluetooth headphones}),0.034755,0.068334,0.011921,0.342995,5.019359,1.0,0.009546,1.418050,0.829604,0.130755,0.294806,0.258721
2,frozenset({airpods}),"frozenset({energy drink, bluetooth headphones})",0.122565,0.019980,0.011921,0.097260,4.867918,1.0,0.009472,1.085607,0.905564,0.091260,0.078856,0.346949
3,"frozenset({energy drink, bluetooth headphones})",frozenset({airpods}),0.019980,0.122565,0.011921,0.596639,4.867918,1.0,0.009472,2.175306,0.810772,0.091260,0.540295,0.346949
4,"frozenset({airpods, bluetooth headphones})",frozenset({energy drink}),0.032404,0.084788,0.011921,0.367876,4.338747,1.0,0.009173,1.447835,0.795290,0.113238,0.309313,0.254235
5,frozenset({energy drink}),"frozenset({airpods, bluetooth headphones})",0.084788,0.032404,0.011921,0.140594,4.338747,1.0,0.009173,1.125889,0.840810,0.113238,0.111813,0.254235
6,frozenset({bluetooth headphones}),frozenset({airpods}),0.068334,0.122565,0.032404,0.474201,3.868964,1.0,0.024029,1.668766,0.795922,0.204449,0.400755,0.369293
7,frozenset({airpods}),frozenset({bluetooth headphones}),0.122565,0.068334,0.032404,0.264384,3.868964,1.0,0.024029,1.266510,0.845115,0.204449,0.210429,0.369293
8,frozenset({bluetooth headphones}),frozenset({laptop}),0.068334,0.047179,0.012424,0.181818,3.853769,1.0,0.009200,1.164559,0.794828,0.120521,0.141306,0.222582
9,frozenset({laptop}),frozenset({bluetooth headphones}),0.047179,0.068334,0.012424,0.263345,3.853769,1.0,0.009200,1.264725,0.777181,0.120521,0.209314,0.222582
10,frozenset({laptop}),frozenset({airpods}),0.047179,0.122565,0.020651,0.437722,3.571335,1.0,0.014869,1.560501,0.755643,0.138514,0.359180,0.303108
11,frozenset({airpods}),frozenset({laptop}),0.122565,0.047179,0.020651,0.168493,3.571335,1.0,0.014869,1.145896,0.820566,0.138514,0.127321,0.303108
12,frozenset({iphone 10}),frozenset({airpods}),0.051377,0.122565,0.022330,0.434641,3.546190,1.0,0.016033,1.551994,0.756894,0.147287,0.355668,0.308416
13,frozenset({airpods}),frozenset({iphone 10}),0.122565,0.051377,0.022330,0.182192,3.546190,1.0,0.016033,1.159958,0.818303,0.147287,0.137900,0.308416
14,frozenset({iphone 10}),frozenset({bluetooth headphones}),0.051377,0.068334,0.012424,0.241830,3.538919,1.0,0.008914,1.228835,0.756283,0.115806,0.186221,0.211824
15,frozenset({bluetooth headphones}),frozenset({iphone 10}),0.068334,0.051377,0.012424,0.181818,3.538919,1.0,0.008914,1.159428,0.770049,0.115806,0.137506,0.211824
16,frozenset({bluetooth headphones}),frozenset({energy drink}),0.068334,0.084788,0.019980,0.292383,3.448386,1.0,0.014186,1.293372,0.762086,0.150063,0.226827,0.264013
17,frozenset({energy drink}),frozenset({bluetooth headphones}),0.084788,0.068334,0.019980,0.235644,3.448386,1.0,0.014186,1.218889,0.775787,0.150063,0.179581,0.264013
18,frozenset({energy drink}),frozenset({gadget for tiktok streaming}),0.084788,0.040463,0.011753,0.138614,3.425660,1.0,0.008322,1.113945,0.773685,0.103550,0.102289,0.214535
19,frozenset({gadget for tiktok streaming}),frozenset({energy drink}),0.040463,0.084788,0.011753,0.290456,3.425660,1.0,0.008322,1.289860,0.737945,0.103550,0.224722,0.214535
20,frozenset({airpods}),frozenset({megaman zero 4}),0.122565,0.030557,0.012592,0.102740,3.362186,1.0,0.008847,1.080447,0.800714,0.089606,0.074458,0.257414
21,frozenset({megaman zero 4}),frozenset({airpods}),0.030557,0.122565,0.012592,0.412088,3.362186,1.0,0.008847,1.492459,0.724720,0.089606,0.329965,0.257414
22,frozenset({energy drink}),frozenset({airpods}),0.084788,0.122565,0.034755,0.409901,3.344343,1.0,0.024363,1.486928,0.765930,0.201362,0.327472,0.346731
23,frozenset({airpods}),frozenset({energy drink}),0.122565,0.084788,0.034755,0.283562,3.344343,1.0,0.024363,1.277446,0.798906,0.201362,0.217188,0.346731
24,frozenset({energy drink}),frozenset({iphone 10}),0.084788,0.051377,0.014271,0.168317,3.276128,1.0,0.009915,1.140607,0.759127,0.117080,0.123273,0.223047
25,frozenset({iphone 10}),frozenset({energy drink}),0.051377,0.084788,0.014271,0.277778,3.276128,1.0,0.009915,1.267216,0.732389,0.117080,0.210869,0.223047
26,frozenset({laptop}),frozenset({energy drink}),0.047179,0.084788,0.013096,0.277580,3.273796,1.0,0.009096,1.266869,0.728935,0.110169,0.210653,0.216018
27,frozenset({energy drink}),frozenset({laptop}),0.084788,0.047179,0.013096,0.154455,3.273796,1.0,0.009096,1.126872,0.758889,0.110169,0.112588,0.216018
28,frozenset({airpods}),frozenset({portal 2}),0.122565,0.029214,0.011417,0.093151,3.188537,1.0,0.007836,1.070504,0.782254,0.081340,0.065861,0.241978
29,frozenset({portal 2}),frozenset({airpods}),0.029214,0.122565,0.011417,0.390805,3.188537,1.0,0.007836,1.440317,0.707032,0.081340,0.305708,0.241978

CLUSTER: Vegans

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({salad}),"frozenset({asparagus, avocado})",0.250894,0.153666,0.067948,0.270824,1.762424,1.0,0.029394,1.160672,0.577488,0.201859,0.138430,0.356503
1,"frozenset({asparagus, avocado})",frozenset({salad}),0.153666,0.250894,0.067948,0.442182,1.762424,1.0,0.029394,1.342921,0.511145,0.201859,0.255355,0.356503
2,"frozenset({asparagus, spinach})",frozenset({salad}),0.156571,0.250894,0.068619,0.438258,1.746787,1.0,0.029336,1.333542,0.506884,0.202507,0.250117,0.355878
3,frozenset({salad}),"frozenset({asparagus, spinach})",0.250894,0.156571,0.068619,0.273497,1.746787,1.0,0.029336,1.160943,0.570707,0.202507,0.138631,0.355878
4,frozenset({salad}),"frozenset({asparagus, carrots})",0.250894,0.147072,0.064260,0.256125,1.741492,1.0,0.027361,1.146601,0.568384,0.192565,0.127857,0.346527
5,"frozenset({asparagus, carrots})",frozenset({salad}),0.147072,0.250894,0.064260,0.436930,1.741492,1.0,0.027361,1.330396,0.499198,0.192565,0.248344,0.346527
6,"frozenset({asparagus, tomatoes})",frozenset({salad}),0.148637,0.250894,0.064372,0.433083,1.726158,1.0,0.027080,1.321367,0.494123,0.192064,0.243208,0.344826
7,frozenset({salad}),"frozenset({asparagus, tomatoes})",0.250894,0.148637,0.064372,0.256570,1.726158,1.0,0.027080,1.145183,0.561574,0.192064,0.126777,0.344826
8,"frozenset({asparagus, carrots})",frozenset({spinach}),0.147072,0.258494,0.065266,0.443769,1.716751,1.0,0.027249,1.333091,0.489495,0.191790,0.249864,0.348127
9,frozenset({spinach}),"frozenset({asparagus, carrots})",0.258494,0.147072,0.065266,0.252486,1.716751,1.0,0.027249,1.141019,0.563049,0.191790,0.123591,0.348127
10,"frozenset({asparagus, tomatoes})",frozenset({spinach}),0.148637,0.258494,0.065042,0.437594,1.692863,1.0,0.026621,1.318454,0.480740,0.190134,0.241536,0.344608
11,frozenset({spinach}),"frozenset({asparagus, tomatoes})",0.258494,0.148637,0.065042,0.251621,1.692863,1.0,0.026621,1.137610,0.551964,0.190134,0.120964,0.344608
12,"frozenset({asparagus, salad})",frozenset({avocado}),0.157689,0.255141,0.067948,0.430900,1.688872,1.0,0.027715,1.308837,0.484249,0.197019,0.235963,0.348608
13,frozenset({avocado}),"frozenset({asparagus, salad})",0.255141,0.157689,0.067948,0.266316,1.688872,1.0,0.027715,1.148057,0.547605,0.197019,0.128963,0.348608
14,"frozenset({asparagus, salad})",frozenset({spinach}),0.157689,0.258494,0.068619,0.435152,1.683417,1.0,0.027857,1.312755,0.481972,0.197428,0.238243,0.350304
15,frozenset({spinach}),"frozenset({asparagus, salad})",0.258494,0.157689,0.068619,0.265456,1.683417,1.0,0.027857,1.146713,0.547494,0.197428,0.127942,0.350304
16,frozenset({asparagus}),"frozenset({salad, avocado})",0.416853,0.097340,0.067948,0.163003,1.674567,1.0,0.027372,1.078450,0.690788,0.152266,0.072743,0.430525
17,"frozenset({salad, avocado})",frozenset({asparagus}),0.097340,0.416853,0.067948,0.698048,1.674567,1.0,0.027372,1.931259,0.446271,0.152266,0.482203,0.430525
18,frozenset({spinach}),"frozenset({asparagus, avocado})",0.258494,0.153666,0.066495,0.257242,1.674035,1.0,0.026774,1.139448,0.543004,0.192370,0.122382,0.344984
19,"frozenset({asparagus, avocado})",frozenset({spinach}),0.153666,0.258494,0.066495,0.432727,1.674035,1.0,0.026774,1.307143,0.475747,0.192370,0.234973,0.344984
20,frozenset({avocado}),"frozenset({asparagus, tomatoes})",0.255141,0.148637,0.063254,0.247919,1.667957,1.0,0.025331,1.132011,0.537637,0.185756,0.116616,0.336742
21,"frozenset({asparagus, tomatoes})",frozenset({avocado}),0.148637,0.255141,0.063254,0.425564,1.667957,1.0,0.025331,1.296679,0.470380,0.185756,0.228799,0.336742
22,frozenset({avocado}),"frozenset({asparagus, spinach})",0.255141,0.156571,0.066495,0.260622,1.664558,1.0,0.026548,1.140727,0.535994,0.192619,0.123366,0.342659
23,"frozenset({asparagus, spinach})",frozenset({avocado}),0.156571,0.255141,0.066495,0.424697,1.664558,1.0,0.026548,1.294724,0.473353,0.192619,0.227635,0.342659
24,"frozenset({asparagus, carrots})",frozenset({avocado}),0.147072,0.255141,0.062360,0.424012,1.661875,1.0,0.024836,1.293186,0.466945,0.183492,0.226716,0.334214
25,frozenset({avocado}),"frozenset({asparagus, carrots})",0.255141,0.147072,0.062360,0.244415,1.661875,1.0,0.024836,1.128832,0.534692,0.183492,0.114128,0.334214
26,"frozenset({asparagus, spinach})",frozenset({carrots}),0.156571,0.251341,0.065266,0.416845,1.658484,1.0,0.025913,1.283808,0.470745,0.190476,0.221067,0.338258
27,frozenset({carrots}),"frozenset({asparagus, spinach})",0.251341,0.156571,0.065266,0.259671,1.658484,1.0,0.025913,1.139262,0.530334,0.190476,0.122239,0.338258
28,"frozenset({salad, spinach})",frozenset({asparagus}),0.100358,0.416853,0.068619,0.683742,1.640247,1.0,0.026784,1.843895,0.433879,0.152965,0.457670,0.424176
29,frozenset({asparagus}),"frozenset({salad, spinach})",0.416853,0.100358,0.068619,0.164611,1.640247,1.0,0.026784,1.076915,0.669361,0.152965,0.071421,0.424176

CLUSTER: Big families (big spenders)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({airpods}),frozenset({energy drink}),0.075826,0.058612,0.011047,0.145686,2.485592,1.0,0.006602,1.101922,0.646719,0.089526,0.092495,0.167079
1,frozenset({energy drink}),frozenset({airpods}),0.058612,0.075826,0.011047,0.188472,2.485592,1.0,0.006602,1.138808,0.634894,0.089526,0.121889,0.167079
2,frozenset({airpods}),frozenset({bluetooth headphones}),0.075826,0.058719,0.010779,0.142150,2.420833,1.0,0.006326,1.097255,0.635074,0.087088,0.088635,0.162856
3,frozenset({bluetooth headphones}),frozenset({airpods}),0.058719,0.075826,0.010779,0.183562,2.420833,1.0,0.006326,1.131958,0.623532,0.087088,0.116575,0.162856
4,frozenset({napkins}),"frozenset({toilet paper, dog food})",0.185221,0.037913,0.014532,0.078460,2.069473,1.0,0.007510,1.043999,0.634264,0.069666,0.042145,0.230885
5,"frozenset({toilet paper, dog food})",frozenset({napkins}),0.037913,0.185221,0.014532,0.383310,2.069473,1.0,0.007510,1.321213,0.537150,0.069666,0.243120,0.230885
6,frozenset({napkins}),"frozenset({chicken, dog food})",0.185221,0.036304,0.013889,0.074986,2.065480,1.0,0.007165,1.041817,0.633118,0.066890,0.040139,0.228778
7,"frozenset({chicken, dog food})",frozenset({napkins}),0.036304,0.185221,0.013889,0.382570,2.065480,1.0,0.007165,1.319630,0.535284,0.066890,0.242212,0.228778
8,frozenset({napkins}),"frozenset({fresh bread, cooking oil})",0.185221,0.031478,0.011958,0.064563,2.051052,1.0,0.006128,1.035368,0.628938,0.058408,0.034160,0.222230
9,"frozenset({fresh bread, cooking oil})",frozenset({napkins}),0.031478,0.185221,0.011958,0.379898,2.051052,1.0,0.006128,1.313943,0.529100,0.058408,0.238932,0.222230
10,"frozenset({cooking oil, toilet paper})",frozenset({napkins}),0.033623,0.185221,0.012763,0.379585,2.049365,1.0,0.006535,1.313281,0.529859,0.061931,0.238549,0.224245
11,frozenset({napkins}),"frozenset({cooking oil, toilet paper})",0.185221,0.033623,0.012763,0.068906,2.049365,1.0,0.006535,1.037894,0.628445,0.061931,0.036510,0.224245
12,"frozenset({cooking oil, dog food})",frozenset({napkins}),0.059577,0.185221,0.022576,0.378938,2.045870,1.0,0.011541,1.311912,0.543596,0.101593,0.237754,0.250413
13,frozenset({napkins}),"frozenset({cooking oil, dog food})",0.185221,0.059577,0.022576,0.121888,2.045870,1.0,0.011541,1.070959,0.627422,0.101593,0.066258,0.250413
14,"frozenset({toilet paper, napkins})",frozenset({dog food}),0.035178,0.202435,0.014532,0.413110,2.040707,1.0,0.007411,1.358969,0.528568,0.065144,0.264148,0.242449
15,frozenset({dog food}),"frozenset({toilet paper, napkins})",0.202435,0.035178,0.014532,0.071788,2.040707,1.0,0.007411,1.039441,0.639413,0.065144,0.037945,0.242449
16,"frozenset({babies food, chicken})",frozenset({napkins}),0.034266,0.185221,0.012924,0.377152,2.036227,1.0,0.006577,1.308150,0.526952,0.062565,0.235562,0.223463
17,frozenset({napkins}),"frozenset({babies food, chicken})",0.185221,0.034266,0.012924,0.069774,2.036227,1.0,0.006577,1.038171,0.624581,0.062565,0.036768,0.223463
18,"frozenset({cooking oil, milk})",frozenset({babies food}),0.033516,0.194230,0.013245,0.395200,2.034702,1.0,0.006736,1.332292,0.526162,0.061750,0.249414,0.231697
19,frozenset({babies food}),"frozenset({cooking oil, milk})",0.194230,0.033516,0.013245,0.068194,2.034702,1.0,0.006736,1.037217,0.631107,0.061750,0.035881,0.231697
20,"frozenset({babies food, milk})",frozenset({cooking oil}),0.036251,0.180019,0.013245,0.365385,2.029697,1.0,0.006720,1.292091,0.526398,0.065240,0.226061,0.219481
21,frozenset({cooking oil}),"frozenset({babies food, milk})",0.180019,0.036251,0.013245,0.073578,2.029697,1.0,0.006720,1.040292,0.618692,0.065240,0.038731,0.219481
22,"frozenset({babies food, napkins})",frozenset({cooking oil}),0.060918,0.180019,0.022147,0.363556,2.019541,1.0,0.011181,1.288379,0.537587,0.101225,0.223831,0.243291
23,frozenset({cooking oil}),"frozenset({babies food, napkins})",0.180019,0.060918,0.022147,0.123027,2.019541,1.0,0.011181,1.070821,0.615671,0.101225,0.066137,0.243291
24,frozenset({cooking oil}),"frozenset({toilet paper, napkins})",0.180019,0.035178,0.012763,0.070897,2.015367,1.0,0.006430,1.038444,0.614420,0.063046,0.037021,0.216851
25,"frozenset({toilet paper, napkins})",frozenset({cooking oil}),0.035178,0.180019,0.012763,0.362805,2.015367,1.0,0.006430,1.286860,0.522182,0.063046,0.222914,0.216851
26,"frozenset({cooking oil, babies food})",frozenset({napkins}),0.059470,0.185221,0.022147,0.372408,2.010613,1.0,0.011132,1.298261,0.534421,0.099518,0.229739,0.245990
27,frozenset({napkins}),"frozenset({cooking oil, babies food})",0.185221,0.059470,0.022147,0.119572,2.010613,1.0,0.011132,1.068264,0.616902,0.099518,0.063902,0.245990
28,frozenset({cooking oil}),"frozenset({cat food, babies food})",0.180019,0.034749,0.012548,0.069705,2.005958,1.0,0.006293,1.037575,0.611581,0.062053,0.036214,0.215408
29,"frozenset({cat food, babies food})",frozenset({cooking oil}),0.034749,0.180019,0.012548,0.361111,2.005958,1.0,0.006293,1.283448,0.519538,0.062053,0.220849,0.215408

CLUSTER: Loyal big spenders

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({cereals}),frozenset({eggs}),0.108562,0.106645,0.028562,0.263096,2.467017,1.0,0.016985,1.212308,0.667071,0.153030,0.175127,0.265460
1,frozenset({eggs}),frozenset({cereals}),0.106645,0.108562,0.028562,0.267825,2.467017,1.0,0.016985,1.217520,0.665640,0.153030,0.178658,0.265460
2,frozenset({butter}),frozenset({eggs}),0.111629,0.106645,0.028498,0.255295,2.393867,1.0,0.016594,1.199608,0.655431,0.150168,0.166395,0.261260
3,frozenset({eggs}),frozenset({butter}),0.106645,0.111629,0.028498,0.267226,2.393867,1.0,0.016594,1.212339,0.651775,0.150168,0.175148,0.261260
4,frozenset({butter}),frozenset({cereals}),0.111629,0.108562,0.028051,0.251288,2.314689,1.0,0.015932,1.190628,0.639346,0.145993,0.160107,0.254838
5,frozenset({cereals}),frozenset({butter}),0.108562,0.111629,0.028051,0.258387,2.314689,1.0,0.015932,1.197890,0.637147,0.145993,0.165199,0.254838
6,frozenset({cereals}),frozenset({fresh bread}),0.108562,0.121981,0.028115,0.258976,2.123087,1.0,0.014872,1.184873,0.593410,0.138889,0.156027,0.244732
7,frozenset({fresh bread}),frozenset({cereals}),0.121981,0.108562,0.028115,0.230487,2.123087,1.0,0.014872,1.158444,0.602478,0.138889,0.136773,0.244732
8,frozenset({fresh bread}),frozenset({eggs}),0.121981,0.106645,0.027540,0.225773,2.117041,1.0,0.014531,1.153866,0.600947,0.136956,0.133348,0.242006
9,frozenset({eggs}),frozenset({fresh bread}),0.106645,0.121981,0.027540,0.258238,2.117041,1.0,0.014531,1.183695,0.590631,0.136956,0.155188,0.242006
10,frozenset({butter}),frozenset({fresh bread}),0.111629,0.121981,0.026965,0.241557,1.980286,1.0,0.013348,1.157660,0.557225,0.130489,0.136189,0.231308
11,frozenset({fresh bread}),frozenset({butter}),0.121981,0.111629,0.026965,0.221058,1.980286,1.0,0.013348,1.140484,0.563795,0.130489,0.123179,0.231308

CLUSTER: Karens

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({shampoo}),frozenset({deodorant}),0.269613,0.281603,0.126756,0.470140,1.669511,1.0,0.050832,1.355823,0.549054,0.298628,0.262441,0.460131
1,frozenset({deodorant}),frozenset({shampoo}),0.281603,0.269613,0.126756,0.450122,1.669511,1.0,0.050832,1.328270,0.558218,0.298628,0.247141,0.460131
2,frozenset({shower gel}),frozenset({shampoo}),0.269613,0.269613,0.119219,0.442186,1.640076,1.0,0.046528,1.309373,0.534336,0.283850,0.236276,0.442186
3,frozenset({shampoo}),frozenset({shower gel}),0.269613,0.269613,0.119219,0.442186,1.640076,1.0,0.046528,1.309373,0.534336,0.283850,0.236276,0.442186
4,frozenset({shower gel}),frozenset({deodorant}),0.269613,0.281603,0.124358,0.461245,1.637926,1.0,0.048434,1.333439,0.533240,0.291332,0.250060,0.451426
5,frozenset({deodorant}),frozenset({shower gel}),0.281603,0.269613,0.124358,0.441606,1.637926,1.0,0.048434,1.308014,0.542140,0.291332,0.235482,0.451426
6,frozenset({deodorant}),frozenset({toothpaste}),0.281603,0.273724,0.124358,0.441606,1.613326,1.0,0.047276,1.300651,0.529182,0.288553,0.231154,0.447962
7,frozenset({toothpaste}),frozenset({deodorant}),0.273724,0.281603,0.124358,0.454318,1.613326,1.0,0.047276,1.316511,0.523441,0.288553,0.240417,0.447962
8,frozenset({shower gel}),frozenset({tooth brush}),0.269613,0.267215,0.116136,0.430750,1.611998,1.0,0.044091,1.287281,0.519795,0.276059,0.223169,0.432683
9,frozenset({tooth brush}),frozenset({shower gel}),0.267215,0.269613,0.116136,0.434615,1.611998,1.0,0.044091,1.291841,0.518094,0.276059,0.225911,0.432683
10,frozenset({toothpaste}),frozenset({tooth brush}),0.273724,0.267215,0.117506,0.429287,1.606523,1.0,0.044363,1.283981,0.519826,0.277508,0.221172,0.434515
11,frozenset({tooth brush}),frozenset({toothpaste}),0.267215,0.273724,0.117506,0.439744,1.606523,1.0,0.044363,1.296328,0.515209,0.277508,0.228590,0.434515
12,frozenset({shampoo}),frozenset({toothpaste}),0.269613,0.273724,0.118191,0.438374,1.601517,1.0,0.044392,1.293166,0.514237,0.278002,0.226704,0.435082
13,frozenset({toothpaste}),frozenset({shampoo}),0.273724,0.269613,0.118191,0.431790,1.601517,1.0,0.044392,1.285417,0.517148,0.278002,0.222042,0.435082
14,frozenset({toothpaste}),frozenset({shower gel}),0.273724,0.269613,0.117506,0.429287,1.592233,1.0,0.043707,1.279779,0.512135,0.275945,0.218615,0.432559
15,frozenset({shower gel}),frozenset({toothpaste}),0.269613,0.273724,0.117506,0.435832,1.592233,1.0,0.043707,1.287341,0.509252,0.275945,0.223205,0.432559
16,frozenset({shampoo}),frozenset({tooth brush}),0.269613,0.267215,0.113052,0.419314,1.569201,1.0,0.041008,1.261930,0.496631,0.266774,0.207563,0.421195
17,frozenset({tooth brush}),frozenset({shampoo}),0.267215,0.269613,0.113052,0.423077,1.569201,1.0,0.041008,1.266004,0.495006,0.266774,0.210113,0.421195
18,frozenset({deodorant}),frozenset({tooth brush}),0.281603,0.267215,0.117506,0.417275,1.561571,1.0,0.042257,1.257514,0.500586,0.272438,0.204781,0.428509
19,frozenset({tooth brush}),frozenset({deodorant}),0.267215,0.281603,0.117506,0.439744,1.561571,1.0,0.042257,1.282264,0.490757,0.272438,0.220129,0.428509

NOTE: after much debugging, we couldn't find the cause root to the label switch between the 'Karens' and 'Clean and healthy' clusters. To fix the promotions to be as intended in the app, we've considered them to be swapped, despite acknowledging the output above is incorrect.

# **4. Promotions**

In the app, you can find promotion in the the "Promotions and Basket" section.